.TH KIOSKWM 1 kioskwm\-VERSION
.SH NAME
kioskwm \- kiosk window manager
.SH SYNOPSIS
.B kioskwm
.RB [ \-v ]
.SH DESCRIPTION
kioskwm is minimalist window manager for X. It tends to place windows in
the center of the screen, and is intended for secured X sessions, such as
public kiosks.
.P
kioskwm draws a small border around windows to indicate the focus state.
.SH OPTIONS
.TP
.B \-v
prints version information to standard output, then exits.
.SH USAGE
.SS Mouse commands
.TP
.B Shift\-Mod1\-Button1
Move focused window while dragging.
.TP
.B Shift\-Mod1\-Button3
Resize focused window while dragging.
